<a href="https://colab.research.google.com/github/StanStarishko/python-programming-for-data/blob/main/Worksheets/5_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using numpy for processing lists of number data

---

## numpy is a high performance array processing library for Python

Python lists can contain any type of data, including objects.  numpy arrays are specialised and can only contain numbers.

You can customise the memory usage so that arrays can use less memory and items are always stored contiguously, which isn't always the case for Python lists.  This means that it is more efficient at storing, and faster at processing, large data sets.

Use numpy arrays to **store and manipulate large lists of numbers** (for other data types use plain Python lists or a panda series)

Use numpy arrays to **process panda series (columns) where these contain numerical data and a large number of records**.

Use numpy arrays to **create new sets of data** to add to a dataframe.

For this course we are going to focus on using numpy arrays as a means of holding and working with a list of data from a pandas dataframe column.


---
## Creating a new numpy array (maybe for a new series or an extended series)

To use numpy, you will need to import it.  The conventional way to import numpy is to import the whole library and use an *alias*

`import numpy as np`

Every time you want to use a function from the numpy library you use the syntax:  

`np.function_name()`  

Create a new numpy array from a Python list of numbers
   
`arr = np.array([1,2,3])`

Or a new numpy matrix from a Python 2 dimensional list of numbers

`matrix = np.array([1,2,3],[4,5,6])`

Create a numpy array from a dataframe column (series):

`arr = df['column name'].to_numpy(datatype)`

where the datatype matches the data type of the column (`df.info()` will give this information if you are unsure).



### Exercise 1 - create a new numpy array to hold the numbers from 1 to 10
---

Write a function called `make_array()` which will:
*   create a list of the numbers 1 to 10     -   *hint: try using range()*
*   create a new numpy array called **new_array** from that list
*   print `new_array`

Expected output:  
`[1 2 3 4 5 6 7 8 9 10] `



In [ ]:
import numpy as np

def make_array():
  # add your code below here

  # create a list of the numbers 1 to 10 - hint: try using range()
  num_list = list(range(1,11))

  # create a new numpy array called new_array from that list
  new_array = np.array(num_list)

  # print new_array
  print(new_array)



# run and test the function against the expected output
make_array()

[ 1  2  3  4  5  6  7  8  9 10]


## Setting the number type in memory

numpy allows you to set the type of number in memory (e.g. `int8`, `int32`) when you create the array.  This allows memory allocation to be as small as possible.  

`new_matrix = np.array([1, 2, 3], np.int8)`    

This creates a list of whole numbers which are all small enough to fit in 1 byte of memory storage.

---
### Exercise 2 - create list of smallish numbers

Write a function which will:
*   accept a parameter **num_list**    
*   create a new numpy array called **new_array** from `num_list`, with data size `int16`
*   print `new_array`  

Test input:  
`[31112, 32321, 24567,456,324,789]`

Expected output:   
```
[31112 32321 24567 456 324 789]
```

In [ ]:
import numpy as np

def create_new_array(num_list):
  # add your code below here to turn num_list into a numpy array

  # create a new numpy array called new_array from num_list, with data size int16
  new_array = np.array(num_list, np.int16)

  # print new_array
  print(new_array)


# run and test the code against the expected output
create_new_array([31112, 32321, 24567,456,324,789])

[31112 32321 24567   456   324   789]


---
### Exercise 3 - create a numpy array from a pandas dataframe column

Write a function which  will first create a dataframe from the titanic data set, and then will create a numpy array from the Fare column.

*Recap*:  *the Fare column is df['Fare'] (assuming your dataframe is called df)*

*  create a dataframe from the data set in the file at this url:  https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv  
*  create a new numpy array called **fare** from the `Fare` column (*remember to specify the data type e.g. np.int32, float64 when using* `df.to_numpy()`)  
*  print the `fare` array

Expected output:  
```
array([  7.25  ,  71.2833,   7.925 , ......  23.45  ,  30.    ,   7.75  ])
```

  

In [ ]:
import pandas as pd
import numpy as np

def is_valid_link(link="",link_name="",autotest=False):
  # link always isn't empty and must have is string
  return_value = link != "" and isinstance(link, str)

  if not return_value and not autotest: # not print if autotest
    print(f"{link_name} is not valid")

  return return_value


def create_fare_series(url=""):
  # add your code below here to read the data set into a dataframe and then create a numpy array from the Fare column and print it
  if not is_valid_link(url, "url"):
    return

  # create a dataframe from the data set in the file at url
  df = pd.read_csv(url)

  # create a new numpy array called fare from the Fare column
  fare = df['Fare'].to_numpy(np.float64)
  np.set_printoptions(threshold=6, edgeitems=3, precision=8)

  # print fare
  print(fare)


# run the function and test against the expected output.
url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
create_fare_series(url)

[ 7.25   71.2833  7.925  ... 23.45   30.      7.75  ]


---
### Exercise 4 - get some statistics from a numpy array created from a data series

This exercise will use data on income in certain US states.  The link is: https://github.com/futureCodersSE/python-programming-for-data/blob/main/Datasets/Income-Data.xlsx?raw=True.   This spreadsheet just has one sheet.  

Write a function which will create a numpy array from the `Age` column in the income dataset and will print the following:

*  the average (mean) age of those surveyed  
*  the age of the oldest person
*  the age of the youngest person

TO HELP with this, refer to this helpsheet: http://datacamp-community-prod.s3.amazonaws.com/da466534-51fe-4c6d-b0cb-154f4782eb54

Expected output:  
```
29.88888888888889
42
22
```

     

In [ ]:
import pandas as pd
import numpy as np


def get_excel_data(url="",sheet_name="default"):
  # url and sheet name always isn't empty and must have is string
  is_not_valid_url = not is_valid_link(url,"url")
  is_not_valid_sheet_name = not is_valid_link(sheet_name,"sheet name")
  if is_not_valid_url or is_not_valid_sheet_name:
    return False

  if sheet_name == "default":
    df = pd.read_excel(url)
  else:
    df = pd.read_excel(url,sheet_name)

  return df


def get_age_stats(url="",sheet_name="default"):
  # add your code below here to read the data set into a dataframe and then create a numpy array from the Age column, calculate and print the statistics

  df = get_excel_data(url,sheet_name)
  if df is False:
    return

  # create a numpy array from the Age column
  age = df['Age'].to_numpy(np.int32)

  # the average (mean) age of those surveyed
  print(np.mean(age))

  # the age of the oldest person
  print(np.max(age))

  # the age of the youngest person
  print(np.min(age))


# run the function and test against the expected output.
url = "https://github.com/futureCodersSE/python-programming-for-data/blob/main/Datasets/Income-Data.xlsx?raw=true"
get_age_stats(url)

29.88888888888889
42
22


---
### Exercise 5 - print first 5 and last 5 items in numpy array

Write a function which will use the same array as created in the previous exercise (created from the Age column in the income dataset):

*  print the first 5 items in the array (one per line)
*  print 5 lines of three dots (ie ...)
*  print the last 5 items in the array (one per line)

**Expected output**:  
34  
42  
23  
36  
42  
...  
...  
...  
...  
...  
25  
31  
22  
25  
30  



In [ ]:
import pandas as pd
import numpy as np

def show_head_tail(url="",sheet_name="default"):
  # add your code below here to read the data set into a dataframe and then create a numpy array from the Age column and print the head and tail, with dots as separators

  df = get_excel_data(url,sheet_name)
  if df is False:
    return

  # create a numpy array from the Age column
  age = df['Age'].to_numpy(np.int32)

  # print the first 5 items in the array (one per line)
  for item in age[:5]:
    print(item)

  # print 5 lines of three dots (ie ...)
  for idx in range(5):
    print("...")

  # print the last 5 items in the array (one per line)
  for item in age[-5:]:
    print(item)

# run the function and test against the expected output.
show_head_tail(url)

34
42
23
36
42
...
...
...
...
...
25
31
22
25
30


---
### Exercise 6 - find the mean and standard deviation of wages

This exercise will again use data on income in certain US states.  The link is: https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/Income-Data.xlsx?raw=true  This spreadsheet just has one sheet.

Write a function which will create a numpy array from the `Income` column in the income dataset and will print the following:

*  the mean income of those surveyed  
*  the standard deviation of income
*  the highest income
*  the lowest income as a percentage of the mean (lowest / mean * 100)

TO HELP with this, refer to this helpsheet: http://datacamp-community-prod.s3.amazonaws.com/da466534-51fe-4c6d-b0cb-154f4782eb54

Expected output:  
```
63.388888888888886
13.936916958961463
81
34.70639789658195
```



In [ ]:
import pandas as pd
import numpy as np

def get_income_stats(url="",sheet_name="default"):
  # add your code below to calculate the stats

  df = get_excel_data(url,sheet_name)
  if df is False:
    return

  # create a numpy array from the Income column
  income = df['Income'].to_numpy(np.float64)

  # the mean income of those surveyed
  print(np.mean(income))

  # the standard deviation of income
  print(np.std(income))

  # the highest income
  print(np.max(income))

  # the lowest income as a percentage of the mean (lowest / mean * 100)
  print(np.min(income) / np.mean(income) * 100)


# run the function and test against expected output
get_income_stats(url)

63.388888888888886
13.936916958961463
81.0
34.70639789658195


---
### Exercise 7 - finding the correlation between two series

Let's find out if there is a strong correlation between Age and Income in the income data set.

*  read the Income data into a pandas dataframe
*  create a numpy array from the Age column  
*  create a numpy array from the Income column  
*  use the np.corrcoef(nparray1, nparray2) function to get the Pearson's Correlation Coefficient (the measure of linear correlation between the two data sets) and store it in a variable called **coef**
*  print the correlation coefficient output (see below, it will be a 2x2 matrix)
*  print the correlation coefficient (which is at position [0][1] (coef[0][1]))


Expected output:  
```
[[ 1.         -0.14787412]
 [-0.14787412  1.        ]]
 -0.1478741157606825

```
The matrix gives 4 values showing the correlation between:

```
   |    (Age/Age)        (Age/Income)     |
   |    (Income/Age)     (Income/Income)  |
```
This suggests that income decreases with age (the correlation is negative
so as one increases the other decreases) but that the correlation is quite weak (an absolute correlation would be 1 and no correlation would be 0)

In [ ]:
import pandas as pd
import numpy as np

def get_correlation(url="",sheet_name="default"):
  # add your code below to get the correlation figure for age and salary


  df = get_excel_data(url,sheet_name)
  if df is False:
    return

  # create a numpy array from the Income column
  income = df['Income'].to_numpy(np.float64)

  # create a numpy array from the Age column
  age = df['Age'].to_numpy(np.int32)

  # get the Pearson's Correlation Coefficient (the measure of linear correlation between the two data sets) and store it in a variable called coef
  coef = np.corrcoef(age,income)

  # print the correlation coefficient output (see below, it will be a 2x2 matrix)
  print(coef)

  # print the correlation coefficient (which is at position [0][1] (coef[0][1]))
  print(coef[0][1])



# run the function and test against expected output
get_correlation(url)

[[ 1.         -0.14787412]
 [-0.14787412  1.        ]]
-0.1478741157606825


---
## Broadcasting an operation across an array

Because a numpy array is created from a related set of data, it is useful to be able to operate on every item in the array in the same way.  For instance, the array might hold a set of scores out of 30 and you might want to convert all scores into percentages.

We can do this in a number of ways:  
1.  Create a new array to store the result after the operation in the new array
```
scores = np.array([29,25,15,22,30])
percentages = scores / 30 * 100
print(percentages)
```
Expected output:
```
[ 96.66666667  83.33333333  50.          73.33333333 100.        ]
```
2.  Store the result in the original array
```
scores = np.array([29,25,15,22,30])
scores = scores / 30 * 100
print(scores)
```
Expected output:
```
[ 96.66666667  83.33333333  50.  73.33333333 100. ]
```

Give it a try:





In [ ]:
scores = np.array([29,25,15,22,30]) / 0.3
print(scores)


[ 96.66666667  83.33333333  50.          73.33333333 100.        ]


---
### Exercise 8 - increase whole array by 20

Write a function which will:
*  create a numpy array of 12 numbers
*  create a new array adding 20 to each of the items in the first array  
*  print the new array

Test input:  
`[1,2,3,4,5,6,7,8,1,2,3,4]`

Expected output:  
`[21 22 23 24 25 26 27 28 21 22 23 24]`

In [ ]:
# add your code to define the function to increase all values in an array by 20 and then to call the function
def reset_printoptions_set():
  np.set_printoptions(edgeitems=3,
                      infstr="inf",
                      linewidth=75,
                      nanstr="nan",
                      precision=8,
                      suppress=False,
                      threshold=1000,
                      formatter=None)

def increase_array(num_list, add_value):
  # create and return increased array
  return np.array(num_list) + add_value


# run and test the code against the expected output
reset_printoptions_set()
print(increase_array([1,2,3,4,5,6,7,8,1,2,3,4],20))



[21 22 23 24 25 26 27 28 21 22 23 24]


---
## Conversion of values using broadcasting

---
### Exercise 9 - convert Titanic fares into 21st century values

Write a function which will:  
*  create a dataframe from the titanic data set (https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv)   
*  create a numpy array from the Fare column
*  convert the fares into current value (multiply by a factor of 120.7045 - source https://www.in2013dollars.com/uk/inflation/1912?amount=32 *accessed 22/1/2022*)
*  print the average fare, the maximum fare and the minimum fare

Expected output:  
```
3887.1928207428173
61840.4399214
0.0
```




In [ ]:
import pandas as pd
import numpy as np

def get_current_fares(url=""):
  # add your code below to get the fares data into a numpy array, convert to today's prices and print stats

  if not is_valid_link(url, "url"):
    return

  # create a dataframe from the titanic data set
  df = pd.read_csv(url)

  # create a numpy array from the Fare column
  fare = df['Fare'].to_numpy(np.float64)

  # convert the fares into current value
  fare = fare * 120.7045

  # print the average fare, the maximum fare and the minimum fare
  print(np.mean(fare))
  print(np.max(fare))
  print(np.min(fare))


# run the function and test against expected output
url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
get_current_fares(url)

3887.1928207428173
61840.4399214
0.0


---
### Exercise 10 - create a new column in the dataframe from a numpy array

**Challenging**

Write a function which will calculate expected salaries for all in the income data set after an inflation rate of 3.5% (with results in a new numpy array).

Just to show the result, calculate and print the Pearson Correlation Coefficient between the salaries series and the inflated salaries series.  We would expect this to be 1 (ie the inflated salary is always 3.5% higher than the current salary) and the exercise is just meant to show that - the statistic has no relevance.  

Create a new column in the dataframe from the new numpy array (so that the dataframe now contains the original salaries and the inflated salaries.  
(**Recap**:  *to add a new column, just use* `df['new column name']`)  

To assign a numpy array to a pandas column use  
`df['new column name'] = numpyarrayname.tolist()`

Display the new dataframe and print the correlation coefficient.







In [ ]:
import pandas as pd
import numpy as np

def get_expected_salary(url="",sheet_name="default"):
  # add your code below to get the fares data into a numpy array, calculate the expected salaries and then add this as a new column

  df = get_excel_data(url,sheet_name)
  if df is False:
    return

  # create a numpy array from the Income column
  income = df['Income'].to_numpy(np.float64)

  # calculate the expected salaries
  expected_salary = income * 1.035

  # add this as a new column
  df['Expected Salary'] = expected_salary.tolist()

  # display the new dataframe
  display(df)

  # print the correlation coefficient
  print(np.corrcoef(income,expected_salary))


# run the function and test against the expected output.
url = "https://github.com/futureCodersSE/python-programming-for-data/blob/main/Datasets/Income-Data.xlsx?raw=true"
get_expected_salary(url)




State  County  Population  Age  Income  Expected Salary
0     TX       1          72   34      65           67.275
1     TX       2          33   42      45           46.575
2     TX       5          25   23      46           47.610
3     TX       6          54   36      65           67.275
4     TX       7          11   42      53           54.855
5     TX       8          28   25      62           64.170
6     TX       9          82   35      66           68.310
7     TX      10           5   40      75           77.625
8     MD      11          61   27      22           22.770
9     MD       2           5   23      69           71.415
10    MD       4          98   25      73           75.555
11    MD       3          64   29      75           77.625
12    MD       2          36   24      65           67.275
13    MD       1          24   25      66           68.310
14    MD       5          34   31      78           80.730
15    MD       6          89   22      81           83.835
16    MD       8          21   25      73           75.555
17    MD       7          21   30      62           64.170

[[1. 1.]
 [1. 1.]]


# Reflection
----

## What skills have you demonstrated in completing this notebook?

- attention to detail
- rapid acquisition of new knowledge
- performing routine operations
- tolerance
- endurance

Your answer:

## What caused you the most difficulty?

Your answer:

It was a bit difficult in the 10th challenge to quickly figure out that the salary data can be taken from the table of previous tasks. The first idea was to generate a series of salaries independently with random numbers